name = "MeasureInterface"
uuid = "e1be995b-78f0-4c79-96a2-71f81d4f7996"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
ArraysOfArrays = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
